#!/bin/bash
awk '
/^ *<\/script>/ {
    if (added == 0 && inside_script == 1) {
        print "        // --- NEWS MODULE LOGIC ---"
        print "        const SAMPLE_NEWS = ["
        print "          { id: \"n1\", title: \"Parvat Reality Announces Upcoming Premium Navi Mumbai Land Launch\", date: \"June 28, 2026\", author: \"Sales Desk\", snippet: \"Expanding our greenfield residential luxury landscape footprint with a fresh 40-acre premium project in the booming Navi Mumbai region.\" },"
        print "          { id: \"n2\", title: \"Land Appreciation Rates Soaring in Navi Mumbai Corridors\", date: \"June 15, 2026\", author: \"Economic Times (Repr.)\", snippet: \"With the airport phase completion near, developers report record land inquiries for commercial and logistics plots.\" },"
        print "          { id: \"n3\", title: \"How Legal Vetting Is Transforming Land Purchases In West Region\", date: \"May 30, 2026\", author: \"Parvat Editorial\", snippet: \"Clear-title verified certificates and transparent digital boundaries have become the absolute standard for premium investors.\" }"
        print "        ];"
        print ""
        print "        function getNews() {"
        print "            const str = localStorage.getItem('\''parvat_news'\'');"
        print "            if (!str) {"
        print "                localStorage.setItem('\''parvat_news'\'', JSON.stringify(SAMPLE_NEWS));"
        print "                return SAMPLE_NEWS;"
        print "            }"
        print "            return JSON.parse(str);"
        print "        }"
        print ""
        print "        function saveNews(news) {"
        print "            localStorage.setItem('\''parvat_news'\'', JSON.stringify(news));"
        print "            renderNewsTable();"
        print "        }"
        print ""
        print "        function openNewsModule() {"
        print "            document.getElementById('\''dashboard-home'\'').classList.add('\''hidden'\'');"
        print "            document.getElementById('\''news-module'\'').classList.remove('\''hidden'\'');"
        print "            renderNewsTable();"
        print "        }"
        print ""
        print "        function closeNewsModule() {"
        print "            document.getElementById('\''news-module'\'').classList.add('\''hidden'\'');"
        print "            document.getElementById('\''dashboard-home'\'').classList.remove('\''hidden'\'');"
        print "        }"
        print ""
        print "        function renderNewsTable() {"
        print "            const news = getNews();"
        print "            const tbody = document.getElementById('\''news-table-body'\'');"
        print "            const emptyState = document.getElementById('\''news-empty-state'\'');"
        print "            tbody.innerHTML = '\'';"
        print "            if (news.length === 0) {"
        print "                emptyState.classList.remove('\''hidden'\'');"
        print "            } else {"
        print "                emptyState.classList.add('\''hidden'\'');"
        print "                news.forEach(item => {"
        print "                    const tr = document.createElement('\''tr'\'');"
        print "                    tr.className = \"hover:bg-slate-50 transition-colors\";"
        print "                    let imgStr = item.image ? `<div class=\"w-10 h-10 rounded bg-slate-100 overflow-hidden flex-shrink-0 border border-slate-200\"><img src=\"${escapeHtml(item.image)}\" class=\"w-full h-full object-cover\"></div>` : `<div class=\"w-10 h-10 rounded bg-rose-50 text-rose-300 flex items-center justify-center font-bold text-xs flex-shrink-0\">TXT</div>`;"
        print "                    tr.innerHTML = `"
        print "                        <td class=\"px-6 py-4 font-semibold text-slate-700 whitespace-nowrap\">${escapeHtml(item.date)}</td>"
        print "                        <td class=\"px-6 py-4\">"
        print "                            <div class=\"flex items-center gap-3\">"
        print "                                ${imgStr}"
        print "                                <div>"
        print "                                    <div class=\"font-bold text-slate-900\">${escapeHtml(item.title)}</div>"
        print "                                    <div class=\"text-[10px] text-slate-400 font-light truncate max-w-[300px]\">${escapeHtml(item.snippet)}</div>"
        print "                                </div>"
        print "                            </div>"
        print "                        </td>"
        print "                        <td class=\"px-6 py-4 font-semibold text-slate-700\">${escapeHtml(item.author)}</td>"
        print "                        <td class=\"px-6 py-4 text-right\">"
        print "                            <button onclick=\"editNews('\''${item.id}'\'')\" class=\"text-xs font-bold uppercase text-blue-600 hover:text-blue-800 transition-colors cursor-pointer px-2 py-1 hover:bg-blue-50 rounded mr-2\">Edit</button>"
        print "                            <button onclick=\"deleteNews('\''${item.id}'\'')\" class=\"text-xs font-bold uppercase text-rose-600 hover:text-rose-800 transition-colors cursor-pointer px-2 py-1 hover:bg-rose-50 rounded\">Delete</button>"
        print "                        </td>"
        print "                    `;"
        print "                    tbody.appendChild(tr);"
        print "                });"
        print "            }"
        print "        }"
        print ""
        print "        function openAddNewsModal() {"
        print "            document.getElementById('\''news-modal-title'\'').innerText = \"CREATE NEWS ITEM\";"
        print "            document.getElementById('\''news-modal-badge'\'').innerText = \"PUBLISH CONTENT\";"
        print "            document.getElementById('\''news-id'\'').value = \"\";"
        print "            document.getElementById('\''news-title'\'').value = \"\";"
        print "            document.getElementById('\''news-author'\'').value = \"Corporate Desk\";"
        print "            let d = new Date();"
        print "            const options = { month: '\''long'\'', day: '\''2-digit'\'', year: '\''numeric'\'' };"
        print "            document.getElementById('\''news-date'\'').value = d.toLocaleDateString('\''en-US'\'', options);"
        print "            document.getElementById('\''news-snippet'\'').value = \"\";"
        print "            document.getElementById('\''news-image'\'').value = \"\";"
        print "            document.getElementById('\''news-video'\'').value = \"\";"
        print "            document.getElementById('\''news-modal'\'').classList.remove('\''hidden'\'');"
        print "        }"
        print ""
        print "        function closeNewsModal() {"
        print "            document.getElementById('\''news-modal'\'').classList.add('\''hidden'\'');"
        print "        }"
        print ""
        print "        function editNews(id) {"
        print "            const newsList = getNews();"
        print "            const item = newsList.find(n => n.id === id);"
        print "            if (!item) return;"
        print "            document.getElementById('\''news-modal-title'\'').innerText = \"EDIT NEWS ITEM\";"
        print "            document.getElementById('\''news-modal-badge'\'').innerText = \"UPDATE CONTENT\";"
        print "            document.getElementById('\''news-id'\'').value = item.id;"
        print "            document.getElementById('\''news-title'\'').value = item.title || \"\";"
        print "            document.getElementById('\''news-author'\'').value = item.author || \"\";"
        print "            document.getElementById('\''news-date'\'').value = item.date || \"\";"
        print "            document.getElementById('\''news-snippet'\'').value = item.snippet || \"\";"
        print "            document.getElementById('\''news-image'\'').value = item.image || \"\";"
        print "            document.getElementById('\''news-video'\'').value = item.videoLink || \"\";"
        print "            document.getElementById('\''news-modal'\'').classList.remove('\''hidden'\'');"
        print "        }"
        print ""
        print "        function handleNewsSubmit(e) {"
        print "            e.preventDefault();"
        print "            const id = document.getElementById('\''news-id'\'').value;"
        print "            const title = document.getElementById('\''news-title'\'').value;"
        print "            const author = document.getElementById('\''news-author'\'').value;"
        print "            const date = document.getElementById('\''news-date'\'').value;"
        print "            const snippet = document.getElementById('\''news-snippet'\'').value;"
        print "            const image = document.getElementById('\''news-image'\'').value;"
        print "            const videoLink = document.getElementById('\''news-video'\'').value;"
        print "            "
        print "            let newsList = getNews();"
        print "            if (id) {"
        print "                // Update existing"
        print "                const idx = newsList.findIndex(n => n.id === id);"
        print "                if (idx !== -1) {"
        print "                    newsList[idx] = { ...newsList[idx], title, author, date, snippet, image, videoLink };"
        print "                }"
        print "            } else {"
        print "                // Create new"
        print "                newsList.unshift({"
        print "                    id: '\''n_'\'' + Date.now(),"
        print "                    title, author, date, snippet, image, videoLink"
        print "                });"
        print "            }"
        print "            saveNews(newsList);"
        print "            closeNewsModal();"
        print "        }"
        print ""
        print "        function deleteNews(id) {"
        print "            if (confirm(\"Are you sure you want to delete this news item?\")) {"
        print "                let newsList = getNews();"
        print "                newsList = newsList.filter(n => n.id !== id);"
        print "                saveNews(newsList);"
        print "            }"
        print "        }"
        print ""
        print "        function escapeHtml(unsafe) {"
        print "            if (!unsafe) return \"\";"
        print "            return unsafe"
        print "                 .replace(/&/g, \"&amp;\")"
        print "                 .replace(/</g, \"&lt;\")"
        print "                 .replace(/>/g, \"&gt;\")"
        print "                 .replace(/\"/g, \"&quot;\")"
        print "                 .replace(/'/g, \"&#039;\");"
        print "        }"
        added = 1
    }
}
/^ *<!-- Script logic -->/ {
    inside_script = 1
}
/^ *<!-- Firebase Auth Module Script -->/ {
    inside_script = 0
}
{ print $0 }
' admin.html > temp.html
mv temp.html admin.html
